GET http://localhost:3000/places?text=r joao neponuceno ssde moura, alto do sumare , 490

###
GET http://localhost:3000/places?text=r Manoel batista neto, alto do sumare , 500

###

@originId=ChIJYYbfVNwHugcRMN7CNzVLHo0

@destinationId=Ek9SLiBNYW5vZWwgQmF0aXN0YSBOZXRvLCA1MDAgLSBBbHRvIGRvIFN1bWFyw6ksIE1vc3NvcsOzIC0gUk4sIDU5NjMzLTcxNSwgQnJhc2lsIjESLwoUChIJYaOE8toHugcRpOwaf49rGEsQ9AMqFAoSCW1BNxPZB7oHEaNe6qHlHQ_n

###

GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}


###

POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "ROTA 3",
    "source_id": "{{originId}}",
    "destination_id": "{{destinationId}}"
}

###

GET http://localhost:3000/routes

###

GET http://localhost:3000/routes/675900fc2af9a8172e3e768b